### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mysticaltech** [tvtoglu/predictr#1]
Hello @tvtoglu, thanks for this apparently amazing lib, but the license is really overly restrictive. Meaning if we want to use your lib in any app, we have to make the whole app open. Too bad really, what a shame, and what a loss!

**Comment by tvtoglu** [comment]
Dear @mysticaltech, thankl you liking _predictr_. I have changed the license to the MIT license. Feel free to use predictr in your closed source app. Let me know which app you're developing. I would be interested to know. 
Cheers

**Comment by mysticaltech** [comment]
Thank you, wonderful! For now just exploring and it seems really solid! Keep up the good work 🙏💙
